apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 975050024946.dkr.ecr.us-west-1.amazonaws.com/react-node-backend:latest
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: ecr-secret
