apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 975050024946.dkr.ecr.us-west-1.amazonaws.com/react-node-frontend:latest
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: ecr-secret
